import { FiGithub } from "react-icons/fi";
import { FaFacebookF } from "react-icons/fa";
import { FaLinkedinIn } from "react-icons/fa";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Social Icons - Left */}
        <div className="fixed bottom-0 left-10 flex flex-col items-center gap-5">
          <a href="#" className=" text-secondary transition-transform duration-300 ease-in-out 
                hover:text-[#64ffda] hover:-translate-y-1">
            <FiGithub className=" " />
          </a>
          <a href="#" className="text-secondary transition-transform duration-300 ease-in-out 
                hover:text-[#64ffda] hover:-translate-y-1">
            <FaFacebookF className="" />
          </a>
          <a
            href="#"
            className="text-secondary transition-transform duration-300 ease-in-out 
                hover:text-[#64ffda] hover:-translate-y-1"
          >
            <FaLinkedinIn className=" " />
          </a>

          <div className="w-[1px] h-24 bg-secondary"></div>
        </div>

        {/* Email - Right */}
        <div className="fixed bottom-0 right-10 flex flex-col items-center gap-5">
          <p
            className="text-secondary text-xs rotate-90 fixed bottom-48 tracking-widest transition-transform duration-300 ease-in-out 
                hover:text-[#64ffda] hover:-translate-y-2"
          >
            brittany.chiang@gmail.com
          </p>
          <div className="w-[1px] h-24 bg-secondary"></div>
        </div>
        {children}
      </body>
    </html>
  );
}
